# Generated by Django 2.1.7 on 2019-08-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFLPlayerSummary',
            fields=[
                ('player', models.TextField(blank=True, db_column='Name', primary_key=True, serialize=False)),
                ('pos', models.TextField(blank=True, db_column='Pos', null=True)),
                ('year', models.BigIntegerField(blank=True, db_column='Year', null=True)),
            ],
        ),
    ]
