# Generated by Django 2.1.7 on 2019-08-07 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_package', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nflplayersummary',
            old_name='player',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='nflplayersummary',
            old_name='pos',
            new_name='Pos',
        ),
        migrations.RenameField(
            model_name='nflplayersummary',
            old_name='year',
            new_name='Year',
        ),
    ]
