# Generated by Django 2.1.7 on 2019-08-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_package', '0005_auto_20190807_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFLSummary',
            fields=[
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('pos', models.TextField(blank=True, db_column='Pos', null=True)),
                ('year', models.BigIntegerField(blank=True, db_column='Year', null=True)),
                ('gp', models.BigIntegerField(blank=True, db_column='GP', null=True)),
                ('average_points_scored', models.TextField(blank=True, db_column='Average Points Scored', null=True)),
                ('std', models.TextField(blank=True, db_column='STD', null=True)),
                ('average_points_allowed', models.TextField(blank=True, db_column='Average Points Allowed', null=True)),
                ('defense_std', models.TextField(blank=True, db_column="Defense's STD", null=True)),
            ],
            options={
                'db_table': 'NFL Summary',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='NFLPlayerSummary',
        ),
    ]
