# Generated by Django 2.1.7 on 2019-08-07 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_package', '0002_auto_20190807_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nflplayersummary',
            old_name='Name',
            new_name='test',
        ),
    ]
