# Generated by Django 2.1.7 on 2019-08-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_package', '0003_auto_20190807_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nflplayersummary',
            name='test',
        ),
        migrations.AddField(
            model_name='nflplayersummary',
            name='Name',
            field=models.TextField(blank=True, db_column='Test', primary_key=True, serialize=False),
        ),
    ]
