# Generated by Django 2.1.7 on 2019-08-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_package', '0004_auto_20190807_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nflplayersummary',
            name='Name',
            field=models.TextField(blank=True, db_column='Name', primary_key=True, serialize=False),
        ),
    ]
