# Generated by Django 2.1.7 on 2019-08-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_package', '0007_nflstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefensiveStats',
            fields=[
                ('oppt', models.TextField(blank=True, db_column='Oppt', primary_key=True, serialize=False)),
                ('week', models.BigIntegerField(blank=True, db_column='Week', null=True)),
                ('pos', models.TextField(blank=True, db_column='Pos', null=True)),
                ('yh_points', models.TextField(blank=True, db_column='YH points', null=True)),
            ],
            options={
                'db_table': 'Defensive Stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DefensiveSummary',
            fields=[
                ('oppt', models.TextField(blank=True, db_column='Oppt', primary_key=True, serialize=False)),
                ('pos', models.TextField(blank=True, db_column='Pos', null=True)),
                ('yh_points', models.TextField(blank=True, db_column='YH points', null=True)),
            ],
            options={
                'db_table': 'Defensive Summary',
                'managed': False,
            },
        ),
    ]
